### ISSUE TITLE
javassist.NotFoundException

### ISSUE THREAD

**Issue by supermomonga** [supermomonga/rukkit#32]
```
[13:51:01 ERROR]: Could not load 'plugins/rukkit-1.0.0-SNAPSHOT-standalone.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.ExceptionInInitializerError
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.10.jar:git-Spigot-5391d73-287ef78]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot-1.10.jar:git-Spigot-5391d73-287ef78]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot-1.10.jar:git-Spigot-5391d73-287ef78]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugins(CraftServer.java:297) [spigot-1.10.jar:git-Spigot-5391d73-287ef78]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.reload(CraftServer.java:744) [spigot-1.10.jar:git-Spigot-5391d73-287ef78]
        at org.bukkit.Bukkit.reload(Bukkit.java:539) [spigot-1.10.jar:git-Spigot-5391d73-287ef78]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [spigot-1.10.jar:git-Spigot-5391d73-287ef78]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.10.jar:git-Spigot-5391d73-287ef78]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646) [spigot-1.10.jar:git-Spigot-5391d73-287ef78]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchServerCommand(CraftServer.java:632) [spigot-1.10.jar:git-Spigot-5391d73-287ef78]
        at net.minecraft.server.v1_10_R1.DedicatedServer.aL(DedicatedServer.java:437) [spigot-1.10.jar:git-Spigot-5391d73-287ef78]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.10.jar:git-Spigot-5391d73-287ef78]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672) [spigot-1.10.jar:git-Spigot-5391d73-287ef78]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571) [spigot-1.10.jar:git-Spigot-5391d73-287ef78]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.ExceptionInInitializerError
        at com.supermomonga.rukkit.JRubyPlugin.<clinit>(JRubyPlugin.java:125) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_91]
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.10.jar:git-Spigot-5391d73-287ef78]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot-1.10.jar:git-Spigot-5391d73-287ef78]
        ... 14 more
Caused by: java.lang.RuntimeException: javassist.NotFoundException: com.supermomonga.rukkit.JRubyPlugin
        at javassist.CtClassType.getClassFile2(CtClassType.java:202) ~[?:?]
        at javassist.compiler.MemberResolver.lookupMethod(MemberResolver.java:98) ~[?:?]
        at javassist.compiler.MemberResolver.lookupMethod(MemberResolver.java:84) ~[?:?]
        at javassist.compiler.TypeChecker.atMethodCallCore(TypeChecker.java:711) ~[?:?]
        at javassist.compiler.TypeChecker.atCallExpr(TypeChecker.java:688) ~[?:?]
        at javassist.compiler.JvstTypeChecker.atCallExpr(JvstTypeChecker.java:157) ~[?:?]
        at javassist.compiler.ast.CallExpr.accept(CallExpr.java:46) ~[?:?]
        at javassist.compiler.CodeGen.doTypeCheck(CodeGen.java:242) ~[?:?]
        at javassist.compiler.CodeGen.atStmnt(CodeGen.java:330) ~[?:?]
        at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50) ~[?:?]
        at javassist.compiler.CodeGen.atMethodBody(CodeGen.java:292) ~[?:?]
        at javassist.compiler.Javac.compileBody(Javac.java:223) ~[?:?]
        at javassist.CtBehavior.setBody(CtBehavior.java:438) ~[?:?]
        at javassist.CtBehavior.setBody(CtBehavior.java:412) ~[?:?]
        at com.supermomonga.rukkit.JRubyPlugin.<clinit>(JRubyPlugin.java:114) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_91]
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.10.jar:git-Spigot-5391d73-287ef78]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot-1.10.jar:git-Spigot-5391d73-287ef78]
        ... 14 more
Caused by: javassist.NotFoundException: com.supermomonga.rukkit.JRubyPlugin
        at javassist.CtClassType.getClassFile2(CtClassType.java:189) ~[?:?]
        at javassist.compiler.MemberResolver.lookupMethod(MemberResolver.java:98) ~[?:?]
        at javassist.compiler.MemberResolver.lookupMethod(MemberResolver.java:84) ~[?:?]
        at javassist.compiler.TypeChecker.atMethodCallCore(TypeChecker.java:711) ~[?:?]
        at javassist.compiler.TypeChecker.atCallExpr(TypeChecker.java:688) ~[?:?]
        at javassist.compiler.JvstTypeChecker.atCallExpr(JvstTypeChecker.java:157) ~[?:?]
        at javassist.compiler.ast.CallExpr.accept(CallExpr.java:46) ~[?:?]
        at javassist.compiler.CodeGen.doTypeCheck(CodeGen.java:242) ~[?:?]
        at javassist.compiler.CodeGen.atStmnt(CodeGen.java:330) ~[?:?]
        at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50) ~[?:?]
        at javassist.compiler.CodeGen.atMethodBody(CodeGen.java:292) ~[?:?]
        at javassist.compiler.Javac.compileBody(Javac.java:223) ~[?:?]
        at javassist.CtBehavior.setBody(CtBehavior.java:438) ~[?:?]
        at javassist.CtBehavior.setBody(CtBehavior.java:412) ~[?:?]
        at com.supermomonga.rukkit.JRubyPlugin.<clinit>(JRubyPlugin.java:114) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_91]
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.10.jar:git-Spigot-5391d73-287ef78]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot-1.10.jar:git-Spigot-5391d73-287ef78]
        ... 14 more
```

**Comment by raa0121** [comment]
これ、どの環境で起きてます？ Docker？

**Comment by supermomonga** [comment]
Docker といえば Docker ですが、関係はなさそう

jar ファイルを更新した際に `/reload` すると発生する気がしますが、再現状況がまだ纏められてないので、何か解ったら追記していく予定
